### ISSUE TITLE
Application Data

### ISSUE THREAD

**Issue by giulianovarriale** [14nrv/buefy-shop#21]
I have cloned `buefy-shop` for study purposes, but I didn't find instructions about how to populate my database. How can I do it? There is some way to import on firebase the database structure and some fake data to test on dev env? And how about product env? How should it work?

**Comment by 14nrv** [comment]
Hi,

You should take a look to #18

**Comment by giulianovarriale** [comment]
Now I got, I just add a key `products` on my realtime database with this json as value: `__tests__/__mocks__/products.json` and it worked. Thanks!
