### ISSUE TITLE
3D Secure

### ISSUE THREAD

**Issue by lucafregoso** [14nrv/buefy-shop#27]
Hi, did you ever tried to handle 3D Secure cards with Stripe? I'm trying to do it but it seems really complex

**Comment by 14nrv** [comment]
Hi,

No, I have never tried
[https://stripe.com/docs/sources/three-d-secure](https://stripe.com/docs/sources/three-d-secure)
[https://stripe.com/docs/sources/three-d-secure/subscriptions](https://stripe.com/docs/sources/three-d-secure/subscriptions)
