### ISSUE TITLE
firebase config undefined

### ISSUE THREAD

**Issue by ahrobinson** [14nrv/buefy-shop#28]
Hi,

When trying to run this project, I am passing in the config, but firebase seems to think it is undefined. However, when I log the config object, I can see that it has the values and is being passed to firebase.initializeApp

Do you have any idea why this could be?

**Comment by 14nrv** [comment]
Hi,

Where did you place the firebase config ? In a .env file ?
Are you on Windows ?

You should take a look to [this issue](https://github.com/14nrv/buefy-shop/issues/25) I think.
Almost all **closed** issues concern the firebase setup.

**Comment by ahrobinson** [comment]
Thanks for the quick response!
I actually placed it directly in the firebase-setup file but I'm pretty sure it was due to proxy issues. I was on my work computer before. Just tried it on my home computer and it started right up. Thanks!
